version: '3'
services:
  app:
    build: 
      context: ./cash-converter
    working_dir: /appcash/
    ports:
     - "7001:7001"
    volumes:
      - cashconverter_static_volume:/appcash/dist/

  nginx:
    image: nginx:latest
    volumes:
      - cashconverter_static_volume:/cash-converter-dist/
      - ./nginx/conf.d/queb-online.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  cashconverter_static_volume:
